name = "ayt-bot"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[env.prod.vars]
ADMIN_UID = ""
BOT_ID = ""
BOT_TOKEN = ""
OLD_MESSAGE_TIMEOUT = 300
SLACK_NOTIFICATION_ENDPOINT = ""
